export * from './Header/Header'
export * from './AboutUs/AboutUs'
export * from './Heading/Heading'
export * from './Tech/Tech'
export * from './Steps/Steps'
export * from './Footer/Footer'
export * from './Gallery/Gallery'
export * from './FAQs/FAQs'
